# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mcetin/_Dev/xox_qlearn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mcetin/_Dev/xox_qlearn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.5/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.16.5/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mcetin/_Dev/xox_qlearn/CMakeFiles /Users/mcetin/_Dev/xox_qlearn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mcetin/_Dev/xox_qlearn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/board.o: src/board.cpp.o

.PHONY : src/board.o

# target to build an object file
src/board.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board.cpp.o
.PHONY : src/board.cpp.o

src/board.i: src/board.cpp.i

.PHONY : src/board.i

# target to preprocess a source file
src/board.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board.cpp.i
.PHONY : src/board.cpp.i

src/board.s: src/board.cpp.s

.PHONY : src/board.s

# target to generate assembly for a file
src/board.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/board.cpp.s
.PHONY : src/board.cpp.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

test/test_board.o: test/test_board.cpp.o

.PHONY : test/test_board.o

# target to build an object file
test/test_board.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_board.cpp.o
.PHONY : test/test_board.cpp.o

test/test_board.i: test/test_board.cpp.i

.PHONY : test/test_board.i

# target to preprocess a source file
test/test_board.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_board.cpp.i
.PHONY : test/test_board.cpp.i

test/test_board.s: test/test_board.cpp.s

.PHONY : test/test_board.s

# target to generate assembly for a file
test/test_board.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_board.cpp.s
.PHONY : test/test_board.cpp.s

test/test_game.o: test/test_game.cpp.o

.PHONY : test/test_game.o

# target to build an object file
test/test_game.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_game.cpp.o
.PHONY : test/test_game.cpp.o

test/test_game.i: test/test_game.cpp.i

.PHONY : test/test_game.i

# target to preprocess a source file
test/test_game.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_game.cpp.i
.PHONY : test/test_game.cpp.i

test/test_game.s: test/test_game.cpp.s

.PHONY : test/test_game.s

# target to generate assembly for a file
test/test_game.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/test/test_game.cpp.s
.PHONY : test/test_game.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... tests"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... test/test_board.o"
	@echo "... test/test_board.i"
	@echo "... test/test_board.s"
	@echo "... test/test_game.o"
	@echo "... test/test_game.i"
	@echo "... test/test_game.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

